import type { Product } from "./types"

export const products: Product[] = [
  // ===== MEN'S WEAR - TOP WEAR =====
  {
    id: "m1",
    name: "Summer Cotton T-Shirt White",
    description: "Breathable cotton t-shirt for summer",
    price: 29.99,
    image: "/images/featured-1-summer-cotton-white.jpg",
    category: "men",
    subcategory: "Top Wear",
    stock: 120,
    rating: 4.6,
    reviews: 340,
    gender: "men",
    discount: 0
  },
  {
    id: "m2",
    name: "Summer Cotton T-Shirt Blue",
    description: "Comfortable blue cotton t-shirt",
    price: 29.99,
    image: "/images/featured-2-summer-cotton-blue.jpg",
    category: "men",
    subcategory: "Top Wear",
    stock: 110,
    rating: 4.5,
    reviews: 320,
    gender: "men",
    discount: 0
  },
  {
    id: "m3",
    name: "Summer Cotton T-Shirt Black",
    description: "Classic black cotton t-shirt",
    price: 29.99,
    image: "/images/featured-3-summer-cotton-black.jpg",
    category: "men",
    subcategory: "Top Wear",
    stock: 135,
    rating: 4.7,
    reviews: 380,
    gender: "men",
    discount: 0
  },
  {
    id: "m4",
    name: "Casual Linen Shirt",
    description: "Lightweight linen shirt for casual wear",
    price: 49.99,
    image: "/images/featured-4-casual-linen-shirt.jpg",
    category: "men",
    subcategory: "Shirts",
    stock: 85,
    rating: 4.4,
    reviews: 250,
    gender: "men",
    discount: 0
  },
  {
    id: "m5",
    name: "Formal White Shirt",
    description: "Professional white dress shirt",
    price: 79.99,
    image: "/images/featured-5-formal-white-shirt.jpg",
    category: "men",
    subcategory: "Shirts",
    stock: 95,
    rating: 4.8,
    reviews: 420,
    gender: "men",
    discount: 0
  },
  {
    id: "m6",
    name: "Formal Blue Shirt",
    description: "Premium blue formal shirt",
    price: 79.99,
    image: "/images/featured-6-formal-blue-shirt.jpg",
    category: "men",
    subcategory: "Shirts",
    stock: 88,
    rating: 4.7,
    reviews: 380,
    gender: "men",
    discount: 0
  },
  {
    id: "m7",
    name: "T-Shirt Combo Pack 3",
    description: "Pack of 3 comfortable t-shirts",
    price: 59.99,
    image: "/images/m7-tshirt-combo-pack.jpg",
    category: "men",
    subcategory: "T-shirts",
    stock: 200,
    rating: 4.6,
    reviews: 520,
    gender: "men",
    discount: 0
  },
  {
    id: "m8",
    name: "Striped Casual Shirt",
    description: "Trendy striped casual shirt",
    price: 45.99,
    image: "/images/m8-striped-casual-shirt.jpg",
    category: "men",
    subcategory: "Shirts",
    stock: 75,
    rating: 4.5,
    reviews: 280,
    gender: "men",
    discount: 0
  },

  // ===== MEN'S WEAR - BOTTOM WEAR =====
  {
    id: "m9",
    name: "Blue Denim Jeans",
    description: "Classic blue denim jeans",
    price: 69.99,
    image: "/images/m9-blue-denim-jeans.jpg",
    category: "men",
    subcategory: "Bottom Wear",
    stock: 150,
    rating: 4.7,
    reviews: 680,
    gender: "men",
    discount: 0
  },
  {
    id: "m10",
    name: "Black Denim Jeans",
    description: "Stylish black denim jeans",
    price: 69.99,
    image: "/images/m10-black-denim-jeans.jpg",
    category: "men",
    subcategory: "Bottom Wear",
    stock: 140,
    rating: 4.6,
    reviews: 620,
    gender: "men",
    discount: 0
  },
  {
    id: "m11",
    name: "Cargo Pants Khaki",
    description: "Multi-pocket cargo pants",
    price: 59.99,
    image: "/images/m11-cargo-pants-khaki.jpg",
    category: "men",
    subcategory: "Bottom Wear",
    stock: 100,
    rating: 4.5,
    reviews: 350,
    gender: "men",
    discount: 0
  },
  {
    id: "m12",
    name: "Cargo Pants Black",
    description: "Black cargo pants with pockets",
    price: 59.99,
    image: "/images/m12-cargo-pants-black.jpg",
    category: "men",
    subcategory: "Bottom Wear",
    stock: 95,
    rating: 4.4,
    reviews: 320,
    gender: "men",
    discount: 0
  },
  {
    id: "m13",
    name: "Baggy Fit Jeans",
    description: "Trendy baggy fit jeans",
    price: 74.99,
    image: "/images/m13-baggy-fit-jeans.jpg",
    category: "men",
    subcategory: "Bottom Wear",
    stock: 80,
    rating: 4.5,
    reviews: 280,
    gender: "men",
    discount: 0
  },
  {
    id: "m14",
    name: "Joggers Black",
    description: "Comfortable black joggers",
    price: 44.99,
    image: "/images/m14-joggers-black.jpg",
    category: "men",
    subcategory: "Bottom Wear",
    stock: 120,
    rating: 4.6,
    reviews: 420,
    gender: "men",
    discount: 0
  },
  {
    id: "m15",
    name: "Joggers Grey",
    description: "Casual grey joggers",
    price: 44.99,
    image: "/images/m15-joggers-grey.jpg",
    category: "men",
    subcategory: "Bottom Wear",
    stock: 110,
    rating: 4.5,
    reviews: 380,
    gender: "men",
    discount: 0
  },
  {
    id: "m16",
    name: "Formal Trousers Black",
    description: "Professional black formal trousers",
    price: 89.99,
    image: "/images/m16-formal-trousers-black.jpg",
    category: "men",
    subcategory: "Bottom Wear",
    stock: 70,
    rating: 4.8,
    reviews: 350,
    gender: "men",
    discount: 0
  },
  {
    id: "m17",
    name: "Dhoti Traditional",
    description: "Traditional dhoti for ethnic wear",
    price: 39.99,
    image: "/images/m17-dhoti-traditional.jpg",
    category: "men",
    subcategory: "Bottom Wear",
    stock: 60,
    rating: 4.5,
    reviews: 200,
    gender: "men",
    discount: 0
  },
  {
    id: "m18",
    name: "Track Pants Navy",
    description: "Navy track pants for sports",
    price: 34.99,
    image: "/images/m18-track-pants-navy.jpg",
    category: "men",
    subcategory: "Bottom Wear",
    stock: 140,
    rating: 4.6,
    reviews: 420,
    gender: "men",
    discount: 0
  },
  {
    id: "m19",
    name: "Shorts Casual Blue",
    description: "Casual blue shorts",
    price: 34.99,
    image: "/images/m19-shorts-casual-blue.jpg",
    category: "men",
    subcategory: "Bottom Wear",
    stock: 130,
    rating: 4.4,
    reviews: 310,
    gender: "men",
    discount: 0
  },
  {
    id: "m20",
    name: "Shorts Casual Black",
    description: "Classic black shorts",
    price: 34.99,
    image: "/images/m20-shorts-casual-black.jpg",
    category: "men",
    subcategory: "Bottom Wear",
    stock: 125,
    rating: 4.5,
    reviews: 340,
    gender: "men",
    discount: 0
  },

  // ===== MEN'S WEAR - ETHNIC WEAR =====
  {
    id: "m21",
    name: "Kurta Pajama White",
    description: "Traditional white kurta pajama",
    price: 84.99,
    image: "/images/m21-kurta-pajama-white.jpg",
    category: "men",
    subcategory: "Ethnic Wear",
    stock: 90,
    rating: 4.7,
    reviews: 380,
    gender: "men",
    discount: 0
  },
  {
    id: "m22",
    name: "Kurta Pajama Blue",
    description: "Blue ethnic kurta pajama",
    price: 84.99,
    image: "/images/m22-kurta-pajama-blue.jpg",
    category: "men",
    subcategory: "Ethnic Wear",
    stock: 85,
    rating: 4.6,
    reviews: 350,
    gender: "men",
    discount: 0
  },
  {
    id: "m23",
    name: "Sherwani Gold",
    description: "Premium gold sherwani",
    price: 249.99,
    image: "/images/m23-sherwani-gold.jpg",
    category: "men",
    subcategory: "Ethnic Wear",
    stock: 40,
    rating: 4.9,
    reviews: 200,
    gender: "men",
    discount: 0
  },
  {
    id: "m24",
    name: "Sherwani Maroon",
    description: "Elegant maroon sherwani",
    price: 249.99,
    image: "/images/m24-sherwani-maroon.jpg",
    category: "men",
    subcategory: "Ethnic Wear",
    stock: 35,
    rating: 4.8,
    reviews: 180,
    gender: "men",
    discount: 0
  },
  {
    id: "m25",
    name: "Jodhpuri Suit Black",
    description: "Black jodhpuri suit",
    price: 199.99,
    image: "/images/m25-jodhpuri-suit-black.jpg",
    category: "men",
    subcategory: "Ethnic Wear",
    stock: 45,
    rating: 4.8,
    reviews: 220,
    gender: "men",
    discount: 0
  },
  {
    id: "m26",
    name: "Jodhpuri Suit Navy",
    description: "Navy jodhpuri suit",
    price: 199.99,
    image: "/images/m26-jodhpuri-suit-navy.jpg",
    category: "men",
    subcategory: "Ethnic Wear",
    stock: 42,
    rating: 4.7,
    reviews: 210,
    gender: "men",
    discount: 0
  },
  {
    id: "m27",
    name: "Wedding Suit Black",
    description: "Premium wedding suit",
    price: 279.99,
    image: "/images/m27-wedding-suit-black.jpg",
    category: "men",
    subcategory: "Ethnic Wear",
    stock: 30,
    rating: 4.9,
    reviews: 150,
    gender: "men",
    discount: 0
  },
  {
    id: "m28",
    name: "Nehru Jacket Black",
    description: "Traditional nehru jacket",
    price: 129.99,
    image: "/images/m28-nehru-jacket-black.jpg",
    category: "men",
    subcategory: "Ethnic Wear",
    stock: 55,
    rating: 4.6,
    reviews: 240,
    gender: "men",
    discount: 0
  },

  // ===== MEN'S WEAR - INNERWEAR =====
  {
    id: "m29",
    name: "Cotton Vest White",
    description: "Classic white cotton vest",
    price: 14.99,
    image: "/images/m29-cotton-vest-white.jpg",
    category: "men",
    subcategory: "Innerwear",
    stock: 200,
    rating: 4.5,
    reviews: 420,
    gender: "men",
    discount: 0
  },
  {
    id: "m30",
    name: "Cotton Vest Pack 3",
    description: "Pack of 3 white cotton vests",
    price: 34.99,
    image: "/images/m30-cotton-vest-pack.jpg",
    category: "men",
    subcategory: "Innerwear",
    stock: 180,
    rating: 4.6,
    reviews: 520,
    gender: "men",
    discount: 0
  },
  {
    id: "m31",
    name: "Thermal Inner Black",
    description: "Thermal innerwear for winter",
    price: 24.99,
    image: "/images/m31-thermal-inner-black.jpg",
    category: "men",
    subcategory: "Innerwear",
    stock: 140,
    rating: 4.7,
    reviews: 380,
    gender: "men",
    discount: 0
  },
  {
    id: "m32",
    name: "Briefs Pack 3",
    description: "Pack of 3 comfortable briefs",
    price: 29.99,
    image: "/images/m32-briefs-pack.jpg",
    category: "men",
    subcategory: "Innerwear",
    stock: 170,
    rating: 4.5,
    reviews: 450,
    gender: "men",
    discount: 0
  },
  {
    id: "m33",
    name: "Boxer Shorts Pack 3",
    description: "Pack of 3 boxer shorts",
    price: 34.99,
    image: "/images/m33-boxer-shorts-pack.jpg",
    category: "men",
    subcategory: "Innerwear",
    stock: 160,
    rating: 4.6,
    reviews: 480,
    gender: "men",
    discount: 0
  },
  {
    id: "m34",
    name: "Trunk Innerwear Pack 2",
    description: "Pack of 2 trunk style innerwear",
    price: 24.99,
    image: "/images/m34-trunk-innerwear-pack.jpg",
    category: "men",
    subcategory: "Innerwear",
    stock: 150,
    rating: 4.5,
    reviews: 360,
    gender: "men",
    discount: 0
  },

  // ===== MEN'S WEAR - SPORTSWEAR =====
  {
    id: "m35",
    name: "Track Pants Black",
    description: "Black sports track pants",
    price: 39.99,
    image: "/images/m35-track-pants-black.jpg",
    category: "men",
    subcategory: "Sportswear",
    stock: 110,
    rating: 4.6,
    reviews: 340,
    gender: "men",
    discount: 0
  },
  {
    id: "m36",
    name: "Track Suit Navy",
    description: "Navy track suit",
    price: 89.99,
    image: "/images/m36-track-suit-navy.jpg",
    category: "men",
    subcategory: "Sportswear",
    stock: 80,
    rating: 4.7,
    reviews: 280,
    gender: "men",
    discount: 0
  },
  {
    id: "m37",
    name: "Gym T-Shirt Black",
    description: "Performance gym t-shirt",
    price: 34.99,
    image: "/images/m37-gym-tshirt-black.jpg",
    category: "men",
    subcategory: "Sportswear",
    stock: 120,
    rating: 4.5,
    reviews: 390,
    gender: "men",
    discount: 0
  },
  {
    id: "m38",
    name: "Gym Shorts Navy",
    description: "Sports gym shorts",
    price: 29.99,
    image: "/images/m38-gym-shorts-navy.jpg",
    category: "men",
    subcategory: "Sportswear",
    stock: 100,
    rating: 4.6,
    reviews: 320,
    gender: "men",
    discount: 0
  },

  // ===== MEN'S WEAR - NIGHTWEAR =====
  {
    id: "m39",
    name: "Pyjama Set Blue",
    description: "Comfortable blue pyjama set",
    price: 44.99,
    image: "/images/m39-pyjama-set-blue.jpg",
    category: "men",
    subcategory: "Nightwear",
    stock: 90,
    rating: 4.6,
    reviews: 280,
    gender: "men",
    discount: 0
  },
  {
    id: "m40",
    name: "Pyjama Set Black",
    description: "Black pyjama set",
    price: 44.99,
    image: "/images/m40-pyjama-set-black.jpg",
    category: "men",
    subcategory: "Nightwear",
    stock: 85,
    rating: 4.5,
    reviews: 260,
    gender: "men",
    discount: 0
  },
  {
    id: "m41",
    name: "Night Suit Grey",
    description: "Comfortable grey night suit",
    price: 54.99,
    image: "/images/m41-night-suit-grey.jpg",
    category: "men",
    subcategory: "Nightwear",
    stock: 75,
    rating: 4.6,
    reviews: 240,
    gender: "men",
    discount: 0
  },
  {
    id: "m42",
    name: "Night Shorts Black",
    description: "Black night shorts",
    price: 24.99,
    image: "/images/m42-night-shorts-black.jpg",
    category: "men",
    subcategory: "Nightwear",
    stock: 110,
    rating: 4.4,
    reviews: 220,
    gender: "men",
    discount: 0
  },

  // ===== MEN'S WEAR - WINTER WEAR =====
  {
    id: "m43",
    name: "Shrug Grey",
    description: "Warm grey shrug",
    price: 54.99,
    image: "/images/m43-shrug-grey.jpg",
    category: "men",
    subcategory: "Winter Wear",
    stock: 80,
    rating: 4.5,
    reviews: 240,
    gender: "men",
    discount: 0
  },
  {
    id: "m44",
    name: "Jacket Black",
    description: "Winter black jacket",
    price: 119.99,
    image: "/images/m44-jacket-black.jpg",
    category: "men",
    subcategory: "Winter Wear",
    stock: 70,
    rating: 4.7,
    reviews: 320,
    gender: "men",
    discount: 0
  },
  {
    id: "m45",
    name: "Jacket Navy",
    description: "Navy winter jacket",
    price: 119.99,
    image: "/images/m45-jacket-navy.jpg",
    category: "men",
    subcategory: "Winter Wear",
    stock: 65,
    rating: 4.6,
    reviews: 300,
    gender: "men",
    discount: 0
  },
  {
    id: "m46",
    name: "Sweater Grey",
    description: "Cozy grey sweater",
    price: 64.99,
    image: "/images/m46-sweater-grey.jpg",
    category: "men",
    subcategory: "Winter Wear",
    stock: 90,
    rating: 4.6,
    reviews: 340,
    gender: "men",
    discount: 0
  },
  {
    id: "m47",
    name: "Sweater Black",
    description: "Black winter sweater",
    price: 64.99,
    image: "/images/m47-sweater-black.jpg",
    category: "men",
    subcategory: "Winter Wear",
    stock: 85,
    rating: 4.5,
    reviews: 310,
    gender: "men",
    discount: 0
  },
  {
    id: "m48",
    name: "Cap Black",
    description: "Classic black winter cap",
    price: 19.99,
    image: "/images/m48-cap-black.jpg",
    category: "men",
    subcategory: "Winter Wear",
    stock: 150,
    rating: 4.4,
    reviews: 280,
    gender: "men",
    discount: 0
  },
  {
    id: "m49",
    name: "Socks Wool Pack 3",
    description: "Pack of 3 warm wool socks",
    price: 24.99,
    image: "/images/m49-socks-wool-pack.jpg",
    category: "men",
    subcategory: "Winter Wear",
    stock: 130,
    rating: 4.5,
    reviews: 350,
    gender: "men",
    discount: 0
  },
  {
    id: "m50",
    name: "Hand Gloves Black",
    description: "Warm black hand gloves",
    price: 34.99,
    image: "/images/m50-hand-gloves-black.jpg",
    category: "men",
    subcategory: "Winter Wear",
    stock: 100,
    rating: 4.6,
    reviews: 240,
    gender: "men",
    discount: 0
  },

  // ===== MEN'S WEAR - FOOTWEAR =====
  {
    id: "m51",
    name: "Party Shoes Black",
    description: "Elegant black party shoes",
    price: 79.99,
    image: "/images/m51-party-shoes-black.jpg",
    category: "men",
    subcategory: "Footwear",
    stock: 60,
    rating: 4.7,
    reviews: 240,
    gender: "men",
    discount: 0
  },
  {
    id: "m52",
    name: "Loafers Brown",
    description: "Casual brown loafers",
    price: 69.99,
    image: "/images/m52-loafers-brown.jpg",
    category: "men",
    subcategory: "Footwear",
    stock: 70,
    rating: 4.6,
    reviews: 280,
    gender: "men",
    discount: 0
  },
  {
    id: "m53",
    name: "Office Shoes Black",
    description: "Professional black office shoes",
    price: 84.99,
    image: "/images/m53-office-shoes-black.jpg",
    category: "men",
    subcategory: "Footwear",
    stock: 75,
    rating: 4.7,
    reviews: 320,
    gender: "men",
    discount: 0
  },
  {
    id: "m54",
    name: "Branded Shoes Nike",
    description: "Nike branded shoes",
    price: 129.99,
    image: "/images/m54-branded-shoes-nike.jpg",
    category: "men",
    subcategory: "Footwear",
    stock: 90,
    rating: 4.8,
    reviews: 420,
    gender: "men",
    discount: 0
  },
  {
    id: "m55",
    name: "Casual Shoes Grey",
    description: "Casual grey shoes",
    price: 64.99,
    image: "/images/m55-casual-shoes-grey.jpg",
    category: "men",
    subcategory: "Footwear",
    stock: 85,
    rating: 4.5,
    reviews: 310,
    gender: "men",
    discount: 0
  },
  {
    id: "m56",
    name: "Sports Shoes Running",
    description: "Professional running sports shoes",
    price: 119.99,
    image: "/images/m56-sports-shoes-running.jpg",
    category: "men",
    subcategory: "Footwear",
    stock: 100,
    rating: 4.8,
    reviews: 480,
    gender: "men",
    discount: 0
  },
  {
    id: "m57",
    name: "Trendy Shoes Blue",
    description: "Trendy blue shoes",
    price: 74.99,
    image: "/images/m57-trendy-shoes-blue.jpg",
    category: "men",
    subcategory: "Footwear",
    stock: 80,
    rating: 4.6,
    reviews: 280,
    gender: "men",
    discount: 0
  },
  {
    id: "m58",
    name: "Flip Flops",
    description: "Comfortable flip flops",
    price: 19.99,
    image: "/images/m58-flip-flops.jpg",
    category: "men",
    subcategory: "Footwear",
    stock: 200,
    rating: 4.4,
    reviews: 420,
    gender: "men",
    discount: 0
  },
  {
    id: "m59",
    name: "Crocs Black",
    description: "Comfortable black crocs",
    price: 49.99,
    image: "/images/m59-crocs-black.jpg",
    category: "men",
    subcategory: "Footwear",
    stock: 120,
    rating: 4.5,
    reviews: 360,
    gender: "men",
    discount: 0
  },
  {
    id: "m60",
    name: "Slippers Comfort",
    description: "Comfortable home slippers",
    price: 29.99,
    image: "/images/m60-slippers-comfort.jpg",
    category: "men",
    subcategory: "Footwear",
    stock: 140,
    rating: 4.6,
    reviews: 340,
    gender: "men",
    discount: 0
  },

  // ===== WOMEN'S WEAR - TOP WEAR =====
  {
    id: "w1",
    name: "Summer Top White",
    description: "Breathable white summer top",
    price: 34.99,
    image: "/images/w1-summer-top-white.jpg",
    category: "women",
    subcategory: "Top Wear",
    stock: 110,
    rating: 4.6,
    reviews: 340,
    gender: "women",
    discount: 0
  },
  {
    id: "w2",
    name: "Casual T-Shirt Blue",
    description: "Casual blue t-shirt",
    price: 29.99,
    image: "/images/w2-casual-tshirt-blue.jpg",
    category: "women",
    subcategory: "Top Wear",
    stock: 130,
    rating: 4.5,
    reviews: 380,
    gender: "women",
    discount: 0
  },
  {
    id: "w3",
    name: "Dress Casual Blue",
    description: "Casual blue dress",
    price: 74.99,
    image: "/images/w3-dress-casual-blue.jpg",
    category: "women",
    subcategory: "Top Wear",
    stock: 80,
    rating: 4.7,
    reviews: 320,
    gender: "women",
    discount: 0
  },
  {
    id: "w4",
    name: "Gown Evening Red",
    description: "Elegant red evening gown",
    price: 149.99,
    image: "/images/w4-gown-evening-red.jpg",
    category: "women",
    subcategory: "Top Wear",
    stock: 40,
    rating: 4.8,
    reviews: 180,
    gender: "women",
    discount: 0
  },
  {
    id: "w5",
    name: "Top Bottom Set Black",
    description: "Black top and bottom set",
    price: 89.99,
    image: "/images/w5-top-bottom-set-black.jpg",
    category: "women",
    subcategory: "Top Wear",
    stock: 60,
    rating: 4.6,
    reviews: 240,
    gender: "women",
    discount: 0
  },
  {
    id: "w6",
    name: "Formal Shirt White",
    description: "Professional white formal shirt",
    price: 69.99,
    image: "/images/w6-formal-shirt-white.jpg",
    category: "women",
    subcategory: "Top Wear",
    stock: 75,
    rating: 4.7,
    reviews: 280,
    gender: "women",
    discount: 0
  },
  {
    id: "w7",
    name: "Jumpsuit Black",
    description: "Chic black jumpsuit",
    price: 99.99,
    image: "/images/w7-jumpsuit-black.jpg",
    category: "women",
    subcategory: "Top Wear",
    stock: 50,
    rating: 4.7,
    reviews: 220,
    gender: "women",
    discount: 0
  },
  {
    id: "w8",
    name: "Trendy Top Crop",
    description: "Trendy crop top",
    price: 39.99,
    image: "/images/w8-trendy-top-crop.jpg",
    category: "women",
    subcategory: "Top Wear",
    stock: 95,
    rating: 4.5,
    reviews: 300,
    gender: "women",
    discount: 0
  },
  {
    id: "w9",
    name: "Tunic Top Navy",
    description: "Navy tunic top",
    price: 44.99,
    image: "/images/w9-tunic-top-navy.jpg",
    category: "women",
    subcategory: "Top Wear",
    stock: 85,
    rating: 4.6,
    reviews: 280,
    gender: "women",
    discount: 0
  },
  {
    id: "w10",
    name: "Gown Casual White",
    description: "Casual white gown",
    price: 84.99,
    image: "/images/w10-gown-casual-white.jpg",
    category: "women",
    subcategory: "Top Wear",
    stock: 70,
    rating: 4.6,
    reviews: 260,
    gender: "women",
    discount: 0
  },

  // ===== WOMEN'S WEAR - BOTTOM WEAR =====
  {
    id: "w11",
    name: "Jeans Blue",
    description: "Blue denim jeans",
    price: 74.99,
    image: "/images/w11-jeans-blue.jpg",
    category: "women",
    subcategory: "Bottom Wear",
    stock: 120,
    rating: 4.7,
    reviews: 420,
    gender: "women",
    discount: 0
  },
  {
    id: "w12",
    name: "Jeans Black",
    description: "Black denim jeans",
    price: 74.99,
    image: "/images/w12-jeans-black.jpg",
    category: "women",
    subcategory: "Bottom Wear",
    stock: 115,
    rating: 4.6,
    reviews: 390,
    gender: "women",
    discount: 0
  },
  {
    id: "w13",
    name: "Jeggings Black",
    description: "Black comfortable jeggings",
    price: 39.99,
    image: "/images/w13-jeggings-black.jpg",
    category: "women",
    subcategory: "Bottom Wear",
    stock: 140,
    rating: 4.6,
    reviews: 440,
    gender: "women",
    discount: 0
  },
  {
    id: "w14",
    name: "Shorts Casual",
    description: "Casual shorts",
    price: 39.99,
    image: "/images/w14-shorts-casual.jpg",
    category: "women",
    subcategory: "Bottom Wear",
    stock: 130,
    rating: 4.5,
    reviews: 360,
    gender: "women",
    discount: 0
  },
  {
    id: "w15",
    name: "Skirt Casual Blue",
    description: "Casual blue skirt",
    price: 54.99,
    image: "/images/w15-skirt-casual-blue.jpg",
    category: "women",
    subcategory: "Bottom Wear",
    stock: 95,
    rating: 4.5,
    reviews: 280,
    gender: "women",
    discount: 0
  },
  {
    id: "w16",
    name: "Leggings Black",
    description: "Comfortable black leggings",
    price: 34.99,
    image: "/images/w16-leggings-black.jpg",
    category: "women",
    subcategory: "Bottom Wear",
    stock: 160,
    rating: 4.6,
    reviews: 520,
    gender: "women",
    discount: 0
  },

  // ===== WOMEN'S WEAR - WINTER WEAR =====
  {
    id: "w17",
    name: "Jacket Black",
    description: "Winter black jacket",
    price: 129.99,
    image: "/images/w17-jacket-black.jpg",
    category: "women",
    subcategory: "Winter Wear",
    stock: 70,
    rating: 4.7,
    reviews: 320,
    gender: "women",
    discount: 0
  },
  {
    id: "w18",
    name: "Sweater Pink",
    description: "Cozy pink sweater",
    price: 69.99,
    image: "/images/w18-sweater-pink.jpg",
    category: "women",
    subcategory: "Winter Wear",
    stock: 85,
    rating: 4.6,
    reviews: 300,
    gender: "women",
    discount: 0
  },
  {
    id: "w19",
    name: "Sweatshirt Grey",
    description: "Grey sweatshirt",
    price: 59.99,
    image: "/images/w19-sweatshirt-grey.jpg",
    category: "women",
    subcategory: "Winter Wear",
    stock: 95,
    rating: 4.5,
    reviews: 340,
    gender: "women",
    discount: 0
  },
  {
    id: "w20",
    name: "Cap Beanie Black",
    description: "Warm black beanie cap",
    price: 24.99,
    image: "/images/w20-cap-beanie-black.jpg",
    category: "women",
    subcategory: "Winter Wear",
    stock: 130,
    rating: 4.5,
    reviews: 300,
    gender: "women",
    discount: 0
  },
  {
    id: "w21",
    name: "Socks Wool Pack 3",
    description: "Pack of 3 warm wool socks",
    price: 24.99,
    image: "/images/w21-socks-wool-pack.jpg",
    category: "women",
    subcategory: "Winter Wear",
    stock: 120,
    rating: 4.5,
    reviews: 320,
    gender: "women",
    discount: 0
  },
  {
    id: "w22",
    name: "Coat Formal Black",
    description: "Formal black coat",
    price: 179.99,
    image: "/images/w22-coat-formal-black.jpg",
    category: "women",
    subcategory: "Winter Wear",
    stock: 50,
    rating: 4.8,
    reviews: 200,
    gender: "women",
    discount: 0
  },
  {
    id: "w23",
    name: "Blazer Navy",
    description: "Navy formal blazer",
    price: 119.99,
    image: "/images/w23-blazer-navy.jpg",
    category: "women",
    subcategory: "Winter Wear",
    stock: 65,
    rating: 4.7,
    reviews: 280,
    gender: "women",
    discount: 0
  },
  {
    id: "w24",
    name: "Waistcoat Black",
    description: "Black formal waistcoat",
    price: 89.99,
    image: "/images/w24-waistcoat-black.jpg",
    category: "women",
    subcategory: "Winter Wear",
    stock: 60,
    rating: 4.6,
    reviews: 220,
    gender: "women",
    discount: 0
  },

  // ===== WOMEN'S WEAR - PLUS SIZE =====
  {
    id: "w25",
    name: "Plus Size Dress Blue",
    description: "Plus size blue dress",
    price: 99.99,
    image: "/images/w25-plus-size-dress-blue.jpg",
    category: "women",
    subcategory: "Plus Size",
    stock: 70,
    rating: 4.6,
    reviews: 240,
    gender: "women",
    discount: 0
  },
  {
    id: "w26",
    name: "Plus Size Gown Red",
    description: "Plus size red gown",
    price: 129.99,
    image: "/images/w26-plus-size-gown-red.jpg",
    category: "women",
    subcategory: "Plus Size",
    stock: 50,
    rating: 4.7,
    reviews: 180,
    gender: "women",
    discount: 0
  },
  {
    id: "w27",
    name: "Plus Size Top Black",
    description: "Plus size black top",
    price: 54.99,
    image: "/images/w27-plus-size-top-black.jpg",
    category: "women",
    subcategory: "Plus Size",
    stock: 80,
    rating: 4.5,
    reviews: 220,
    gender: "women",
    discount: 0
  },
  {
    id: "w28",
    name: "Plus Size Jeans",
    description: "Plus size blue jeans",
    price: 89.99,
    image: "/images/w28-plus-size-jeans.jpg",
    category: "women",
    subcategory: "Plus Size",
    stock: 75,
    rating: 4.6,
    reviews: 260,
    gender: "women",
    discount: 0
  },
  {
    id: "w29",
    name: "Plus Size Bottom Wear",
    description: "Plus size trousers",
    price: 79.99,
    image: "/images/w29-plus-size-bottom-wear.jpg",
    category: "women",
    subcategory: "Plus Size",
    stock: 70,
    rating: 4.5,
    reviews: 200,
    gender: "women",
    discount: 0
  },

  // ===== WOMEN'S WEAR - INNERWEAR =====
  {
    id: "w30",
    name: "Bra Black",
    description: "Comfortable black bra",
    price: 44.99,
    image: "/images/w30-bra-black.jpg",
    category: "women",
    subcategory: "Innerwear",
    stock: 120,
    rating: 4.6,
    reviews: 380,
    gender: "women",
    discount: 0
  },
  {
    id: "w31",
    name: "Bralette Comfort",
    description: "Comfortable bralette",
    price: 34.99,
    image: "/images/w31-bralette-comfort.jpg",
    category: "women",
    subcategory: "Innerwear",
    stock: 140,
    rating: 4.5,
    reviews: 420,
    gender: "women",
    discount: 0
  },
  {
    id: "w32",
    name: "Panties Pack 3",
    description: "Pack of 3 comfortable panties",
    price: 34.99,
    image: "/images/w32-panties-pack.jpg",
    category: "women",
    subcategory: "Innerwear",
    stock: 150,
    rating: 4.5,
    reviews: 480,
    gender: "women",
    discount: 0
  },
  {
    id: "w33",
    name: "Lingerie Set Black",
    description: "Black lingerie set",
    price: 79.99,
    image: "/images/w33-lingerie-set-black.jpg",
    category: "women",
    subcategory: "Innerwear",
    stock: 80,
    rating: 4.7,
    reviews: 280,
    gender: "women",
    discount: 0
  },
  {
    id: "w34",
    name: "Shapewear Black",
    description: "Black shapewear",
    price: 64.99,
    image: "/images/w34-shapewear-black.jpg",
    category: "women",
    subcategory: "Innerwear",
    stock: 90,
    rating: 4.6,
    reviews: 240,
    gender: "women",
    discount: 0
  },
  {
    id: "w35",
    name: "Camisole White",
    description: "White camisole",
    price: 24.99,
    image: "/images/w35-camisole-white.jpg",
    category: "women",
    subcategory: "Innerwear",
    stock: 130,
    rating: 4.5,
    reviews: 320,
    gender: "women",
    discount: 0
  },
  {
    id: "w36",
    name: "Strappy Innerwear",
    description: "Strappy innerwear",
    price: 29.99,
    image: "/images/w36-strappy-innerwear.jpg",
    category: "women",
    subcategory: "Innerwear",
    stock: 120,
    rating: 4.4,
    reviews: 280,
    gender: "women",
    discount: 0
  },

  // ===== WOMEN'S WEAR - SLEEPWEAR =====
  {
    id: "w37",
    name: "Night Suit Blue",
    description: "Blue night suit",
    price: 54.99,
    image: "/images/w37-night-suit-blue.jpg",
    category: "women",
    subcategory: "Sleepwear",
    stock: 90,
    rating: 4.6,
    reviews: 280,
    gender: "women",
    discount: 0
  },
  {
    id: "w38",
    name: "Night Suit Pink",
    description: "Pink night suit",
    price: 54.99,
    image: "/images/w38-night-suit-pink.jpg",
    category: "women",
    subcategory: "Sleepwear",
    stock: 80,
    rating: 4.5,
    reviews: 260,
    gender: "women",
    discount: 0
  },
  {
    id: "w39",
    name: "Pyjama Set Purple",
    description: "Purple pyjama set",
    price: 49.99,
    image: "/images/w39-pyjama-set-purple.jpg",
    category: "women",
    subcategory: "Sleepwear",
    stock: 90,
    rating: 4.6,
    reviews: 300,
    gender: "women",
    discount: 0
  },
  {
    id: "w40",
    name: "Sleepwear Shorts",
    description: "Comfortable sleep shorts",
    price: 29.99,
    image: "/images/w40-sleepwear-shorts.jpg",
    category: "women",
    subcategory: "Sleepwear",
    stock: 110,
    rating: 4.4,
    reviews: 280,
    gender: "women",
    discount: 0
  },

  // ===== WOMEN'S WEAR - SPORTSWEAR =====
  {
    id: "w41",
    name: "Sports Leggings Black",
    description: "Black sports leggings",
    price: 59.99,
    image: "/images/w41-sports-leggings-black.jpg",
    category: "women",
    subcategory: "Sportswear",
    stock: 100,
    rating: 4.7,
    reviews: 340,
    gender: "women",
    discount: 0
  },
  {
    id: "w42",
    name: "Sports Bra Black",
    description: "Black sports bra",
    price: 54.99,
    image: "/images/w42-sports-bra-black.jpg",
    category: "women",
    subcategory: "Sportswear",
    stock: 90,
    rating: 4.6,
    reviews: 280,
    gender: "women",
    discount: 0
  },
  {
    id: "w43",
    name: "Gym Top Navy",
    description: "Navy gym top",
    price: 39.99,
    image: "/images/w43-gym-top-navy.jpg",
    category: "women",
    subcategory: "Sportswear",
    stock: 95,
    rating: 4.5,
    reviews: 260,
    gender: "women",
    discount: 0
  },
  {
    id: "w44",
    name: "Gym Set Blue",
    description: "Blue gym top and bottom set",
    price: 89.99,
    image: "/images/w44-gym-set-blue.jpg",
    category: "women",
    subcategory: "Sportswear",
    stock: 75,
    rating: 4.6,
    reviews: 220,
    gender: "women",
    discount: 0
  },

  // ===== WOMEN'S WEAR - MATERNITY =====
  {
    id: "w45",
    name: "Maternity Kurti Black",
    description: "Black maternity kurti",
    price: 74.99,
    image: "/images/w45-maternity-kurti-black.jpg",
    category: "women",
    subcategory: "Maternity Wear",
    stock: 60,
    rating: 4.6,
    reviews: 180,
    gender: "women",
    discount: 0
  },
  {
    id: "w46",
    name: "Maternity Top White",
    description: "White maternity top",
    price: 54.99,
    image: "/images/w46-maternity-top-white.jpg",
    category: "women",
    subcategory: "Maternity Wear",
    stock: 70,
    rating: 4.5,
    reviews: 200,
    gender: "women",
    discount: 0
  },
  {
    id: "w47",
    name: "Feeding Bra Black",
    description: "Black nursing/feeding bra",
    price: 59.99,
    image: "/images/w47-feeding-bra-black.jpg",
    category: "women",
    subcategory: "Maternity Wear",
    stock: 75,
    rating: 4.6,
    reviews: 220,
    gender: "women",
    discount: 0
  },
  {
    id: "w48",
    name: "Maternity Brief",
    description: "Maternity comfort brief",
    price: 29.99,
    image: "/images/w48-maternity-brief.jpg",
    category: "women",
    subcategory: "Maternity Wear",
    stock: 80,
    rating: 4.5,
    reviews: 240,
    gender: "women",
    discount: 0
  },
  {
    id: "w49",
    name: "Maternity Bottom Wear",
    description: "Maternity leggings",
    price: 64.99,
    image: "/images/w49-maternity-bottom-wear.jpg",
    category: "women",
    subcategory: "Maternity Wear",
    stock: 70,
    rating: 4.6,
    reviews: 200,
    gender: "women",
    discount: 0
  },

  // ===== WOMEN'S FOOTWEAR =====
  {
    id: "w50",
    name: "Heels Red",
    description: "Stylish red heels",
    price: 99.99,
    image: "/images/w50-heels-red.jpg",
    category: "women",
    subcategory: "Footwear",
    stock: 60,
    rating: 4.7,
    reviews: 240,
    gender: "women",
    discount: 0
  },
  {
    id: "w51",
    name: "Sandals Navy",
    description: "Comfortable navy sandals",
    price: 49.99,
    image: "/images/w51-sandals-navy.jpg",
    category: "women",
    subcategory: "Footwear",
    stock: 70,
    rating: 4.6,
    reviews: 280,
    gender: "women",
    discount: 0
  },
  {
    id: "w52",
    name: "Boots Black",
    description: "Winter black boots",
    price: 149.99,
    image: "/images/w52-boots-black.jpg",
    category: "women",
    subcategory: "Footwear",
    stock: 75,
    rating: 4.7,
    reviews: 320,
    gender: "women",
    discount: 0
  },
  {
    id: "w53",
    name: "Sneakers White",
    description: "Casual white sneakers",
    price: 79.99,
    image: "/images/w53-sneakers-white.jpg",
    category: "women",
    subcategory: "Footwear",
    stock: 85,
    rating: 4.5,
    reviews: 310,
    gender: "women",
    discount: 0
  },
  {
    id: "w54",
    name: "Flip Flops Pink",
    description: "Comfortable pink flip flops",
    price: 29.99,
    image: "/images/w54-flip-flops-pink.jpg",
    category: "women",
    subcategory: "Footwear",
    stock: 90,
    rating: 4.6,
    reviews: 280,
    gender: "women",
    discount: 0
  },
  {
    id: "w55",
    name: "Shoes Flat Brown",
    description: "Casual flat brown shoes",
    price: 59.99,
    image: "/images/w55-shoes-flat-brown.jpg",
    category: "women",
    subcategory: "Footwear",
    stock: 100,
    rating: 4.5,
    reviews: 340,
    gender: "women",
    discount: 0
  },
  {
    id: "w56",
    name: "Sports Shoes Running",
    description: "Professional running sports shoes",
    price: 119.99,
    image: "/images/w56-sports-shoes-running.jpg",
    category: "women",
    subcategory: "Footwear",
    stock: 110,
    rating: 4.8,
    reviews: 480,
    gender: "women",
    discount: 0
  },
  {
    id: "w57",
    name: "Trendy Shoes Blue",
    description: "Trendy blue shoes",
    price: 74.99,
    image: "/images/w57-trendy-shoes-blue.jpg",
    category: "women",
    subcategory: "Footwear",
    stock: 80,
    rating: 4.6,
    reviews: 280,
    gender: "women",
    discount: 0
  },
  {
    id: "w58",
    name: "Flip Flops",
    description: "Comfortable flip flops",
    price: 19.99,
    image: "/images/w58-flip-flops.jpg",
    category: "women",
    subcategory: "Footwear",
    stock: 200,
    rating: 4.4,
    reviews: 420,
    gender: "women",
    discount: 0
  },
  {
    id: "w59",
    name: "Crocs Black",
    description: "Comfortable black crocs",
    price: 49.99,
    image: "/images/w59-crocs-black.jpg",
    category: "women",
    subcategory: "Footwear",
    stock: 120,
    rating: 4.5,
    reviews: 360,
    gender: "women",
    discount: 0
  },
  {
    id: "w60",
    name: "Slippers Comfort",
    description: "Comfortable home slippers",
    price: 29.99,
    image: "/images/w60-slippers-comfort.jpg",
    category: "women",
    subcategory: "Footwear",
    stock: 140,
    rating: 4.6,
    reviews: 340,
    gender: "women",
    discount: 0
  },
]
